<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDQ04bL2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDQ04bL2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDQ04bL2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDQ04bL2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDQ04bL2\App_KernelDevDebugContainer([
    'container.build_hash' => 'DQ04bL2',
    'container.build_id' => '695945be',
    'container.build_time' => 1726471857,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDQ04bL2');
